### PR TITLE
adding headless chrome stack

### PR DESCRIPTION
**Pull request by alpeware**

### CODE REVIEW

**Comment by marcosnils** [comment]
Hey thx for the PR!. In order for the image to work in hub you need to create your stack in it in alpeware/chrome-headless-trunk/latest/stack.yml. Otherwise it won't work.

**Comment by alpeware** [comment]
My bad. Thanks! Should be fixed.

**Comment by marcosnils** [comment]
@alpeware have a question after running this img in PWD. We usually try to make stacks to showcase something, for what I've seen this there's not to much to do after running this stack in PWD. Is there something that could be added to the stack to show a concrete example?

**Comment by alpeware** [comment]
Well, this runs the latest chrome headless so you get a full browser. You
can do anything that your locally installed browser can do.

If you open the 9222 port, you will get a DevTools view. In chrome you have
to accept the load unsafe scripts alert in the URL bar. Once done, you can
surf the web :)

I'm planning on writing up some instructions with a view screenshots in the
next couple days as well and adding your new button to Docker/GitHub.

Let me know if you have any questions or other suggestions in the meantime.



On May 20, 2017 11:11 PM, "Marcos Nils" <notifications@github.com> wrote:

@alpeware <https://github.com/alpeware> have a question after running this
img in PWD. We usually try to make stacks to showcase something, for what
I've seen this there's not to much to do after running this stack in PWD.
Is there something that could be added to the stack to show a concrete
example?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/play-with-docker/stacks/pull/1#issuecomment-302899079>,
or mute the thread

**Comment by marcosnils** [comment]
> In chrome you have
> to accept the load unsafe scripts alert in the URL bar. Once done, you can
> surf the web :)

Is that people would do?. Wouldn't this be a security risk somehow?

**Comment by alpeware** [comment]
Anyone familiar with accessing Chrome's remote debugging protocol.

Normally, you'd use a different client library to connect to your remote
instance and do something programmatically, like run some e2e or
integration tests.

I can look into options to avoid the security alert by maybe bundling the
DevTools or similar.

**Comment by marcosnils** [comment]
> I can look into options to avoid the security alert by maybe bundling the
> DevTools or similar.

Can you bundle DevTools in a container and access it through the browser?. That way, I can deploy both DevTools and Chrome headless and access DevTools through my browser. It'd be browsing inception :). 

I like the idea? ;)

**Comment by alpeware** [comment]
Yup, that'd be the idea. We could then access play with docker through a
chrome instance running on play with docker :)

I'll give it a shot when I get a chance.

**Comment by marcosnils** [comment]
Cool, can't wait to see it :)

**Pull request merged**
